'use client';
import {RULES} from '../lib/rules.mjs';
import MarketChart from './MarketChart.jsx';
import OrderPanel from './OrderPanel.jsx';
import {useState,useEffect,useRef,useCallback} from 'react';
import {BarChart3,Users,Timer,Wallet,ShieldCheck,LockKeyhole,TrendingUp,TrendingDown,Minus,Play,Copy,Check,Maximize2,BookOpen,Trophy,Download,LogOut,RotateCcw,X,Radio,Coins,Monitor,ChevronRight} from 'lucide-react';
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format((v||0)/100);
const date=s=>new Date(s+'T12:00:00').toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'});
const pct=(a,b)=>((a/b-1)*100).toFixed(2);
async function api(body){const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Không thể kết nối.');return data;}
function Chart({values=[],labels=[]}){const vals=values.length?values:[0];let min=Math.min(...vals)*.95,max=Math.max(...vals)*1.05;if(max===min)max=min+1;const pts=vals.map((v,i)=>[24+i*(552/Math.max(1,vals.length-1)),150-(v-min)/(max-min)*124]);return <div className="chart"><svg viewBox="0 0 600 180" role="img" aria-label="Biểu đồ các mốc giá đã công bố"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f74869" stopOpacity=".2"/><stop offset="100%" stopColor="#f74869" stopOpacity="0"/></linearGradient></defs>{[30,70,110,150].map(y=><line key={y} x1="24" y1={y} x2="576" y2={y} stroke="#292b35" strokeDasharray="3 6"/>)}<polygon points={[[24,160],...pts,[pts.at(-1)[0],160]].map(x=>x.join(',')).join(' ')} fill="url(#fill)"/><polyline points={pts.map(x=>x.join(',')).join(' ')} fill="none" stroke="#f74869" strokeWidth="3" strokeLinejoin="round"/>{pts.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="4" fill="#ff6783"/><title>{labels[i]}: {money(vals[i])}</title></g>)}</svg><div className="chart-labels"><span>{labels[0]||'Khởi đầu'}</span><span>{labels.at(-1)||'Chờ quyết định'}</span></div></div>}
function Modal({title,close,children}){const ref=useRef();useEffect(()=>{const prev=document.activeElement;ref.current?.focus();function key(e){if(e.key==='Escape')close();if(e.key==='Tab'){const els=ref.current?.querySelectorAll('button,a,input,select');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prev?.focus();}},[close]);return <div className="overlay" onClick={e=>e.target===e.currentTarget&&close()}><section ref={ref} className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><div className="section-head"><h2>{title}</h2><button className="icon" onClick={close} aria-label="Đóng"><X/></button></div>{children}</section></div>}
function Rules({rules=RULES}){return <div className="rules">
<p>Mỗi người bắt đầu với <b>{money(rules.cash)} tiền mặt + {new Intl.NumberFormat('vi-VN').format(rules.shares)} cổ phiếu NFLX</b>. Tất cả dùng cùng giá và thời hạn.</p>
<div className="rule-row"><strong className="green">BUY</strong><p>{rules.orderMode==='quantity'?'Chọn số cổ phiếu nguyên muốn mua, trong giới hạn tiền mặt. Cổ đang giữ được cộng thêm.':'Dùng tiền mặt mua tối đa cổ phiếu nguyên.'}</p></div>
<div className="rule-row"><strong className="gold">HOLD</strong><p>Giữ nguyên danh mục. Hết {rules.seconds} giây chưa xác nhận cũng là HOLD.</p></div>
<div className="rule-row"><strong className="red">SELL</strong><p>{rules.orderMode==='quantity'?'Chọn số cổ phiếu muốn bán, tối đa bằng số đang giữ.':'Bán toàn bộ cổ phiếu.'} Không vay, bán khống hay phí giao dịch.</p></div>
<p><b>Chốt một lần:</b> xác nhận xong không đổi lệnh. Không ai bị loại; tổng tài sản cao nhất sau 9 vòng thắng. Bằng tài sản thì ưu tiên tổng thời gian phản hồi ngắn hơn; bằng cả hai thì đồng hạng.</p>
<p><b>Chart cùng sự kiện:</b> xem giá lịch sử đến ngày quyết định. Hết giờ mới mở giá đóng cửa phiên kế tiếp. Chạm hoặc di chuột vào điểm trên biểu đồ để xem số liệu.</p>
<p><b>Quy ước mô phỏng:</b> đọc báo cáo vừa công bố và giao dịch ở giá đóng cửa ngày công bố, trước tin; kết quả dùng giá đóng cửa phiên kế tiếp. Đây không phải mức giá bảo đảm có thể mua ngoài đời sau khi biết tin.</p>
<p>Cổ phiếu vẫn chịu biến động giữa các mốc. Tài sản = tiền mặt + cổ phiếu × giá hiện tại. Giá USD đã điều chỉnh chia tách, cùng một thang trên chart và giao dịch.</p>
<p>Lạm phát chỉ hiển thị cuối game: tài sản danh nghĩa × {rules.cpiStart} / {rules.cpiEnd}. Không thay đổi thứ hạng.</p>
</div>}
export default function Game(){
 const [session,setSession]=useState(null),[s,setS]=useState(null),[name,setName]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[modal,setModal]=useState(null),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[online,setOnline]=useState(true),[transport,setTransport]=useState('Đồng bộ'),[copied,setCopied]=useState(false),[replay,setReplay]=useState(''),[restored,setRestored]=useState(false);
 const versionRef=useRef(0);const pending=useRef(false);
 const closeModal=useCallback(()=>setModal(null),[]);
 const accept=useCallback(data=>{setS(data.state);setOffset(data.state.serverNow-Date.now());setOnline(true);},[]);
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem('nflx-session'));if(saved?.token)setSession(saved);const q=new URLSearchParams(location.search).get('room');if(q)setCode(q.toUpperCase());}catch{}setRestored(true);},[]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),200);return()=>clearInterval(id);},[]);
 const refresh=useCallback(async()=>{if(!session||pending.current)return;pending.current=true;const v=++versionRef.current;try{const d=await api({...session,action:'state'});if(v===versionRef.current)accept(d);}catch(e){setOnline(false);setError(e.message);}finally{pending.current=false;}},[session,accept]);
 useEffect(()=>{if(!session)return;refresh();const i=setInterval(refresh,1500);let client;let ended=false;
 (async()=>{try{const r=await fetch('/api/realtime',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(session)});if(!r.ok){setTransport('Đồng bộ HTTP');return;}const initial=await r.json();const Ably=await import('ably');if(ended)return;let first=true;client=new Ably.Realtime({authCallback:async(_,cb)=>{try{if(first){first=false;cb(null,initial);return;}const res=await fetch('/api/realtime',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(session)});if(!res.ok)throw Error('Auth expired');cb(null,await res.json());}catch(e){cb(e.message,null);}}});client.connection.on('connected',()=>setTransport('WebSocket trực tiếp'));client.connection.on('disconnected',()=>setTransport('Đang kết nối lại'));client.channels.get('game:'+session.code).subscribe('changed',refresh);}catch{setTransport('Đồng bộ HTTP');}})();
 return()=>{ended=true;clearInterval(i);client?.close();};},[session,refresh]);
 useEffect(()=>{if(s?.phase==='decision')window.scrollTo({top:0,behavior:'instant'});},[s?.round]);
 async function send(action,extra={}){if(busy)return;setBusy(true);setError('');++versionRef.current;try{const d=await api({...session,action,round:s?.round,phase:s?.phase,...extra});if(d.token){const next={code:d.state.code,token:d.token};sessionStorage.setItem('nflx-session',JSON.stringify(next));setSession(next);}accept(d);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function copy(){try{await navigator.clipboard.writeText(location.origin+'/?room='+s.code);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError('Mã phòng: '+s.code+' — gửi mã này cho người chơi.');}}
 function leave(){sessionStorage.removeItem('nflx-session');setSession(null);setS(null);setError('');setModal(null);}
 function download(){const blob=new Blob([JSON.stringify({room:s.code,rules:s.rules,moneyUnit:'USD cents',players:s.players,replays:s.replays||[{name:s.me?.name,snapshots:s.me?.snapshots}]},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='NFLX-'+s.code+'-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 const rules=s?.rules||RULES;
 const remaining=s?.deadline?Math.min(rules.seconds,Math.max(0,Math.ceil((s.deadline-now-offset)/1000))):rules.seconds;
 const e=s?.event,reveal=s&&['reveal','finished'].includes(s.phase),initial=rules.cash+rules.shares*rules.reference;
 const activeReplay=s?.replays?.find(p=>p.id===replay)||s?.replays?.[0]||s?.me;
 const hasSession=!!session;
 return <main>
  <header className="topbar"><a className="brand" href="/" onClick={ev=>{if(session){ev.preventDefault();setModal('leave');}}}><span className="brand-icon"><BarChart3 size={22}/></span><span>ĐỪNG ĐỂ TIỀN RƠI<small>STOCK MARKET EDITION</small></span></a><div className="top-actions"><span className="edition">NFLX / 2017—2024</span><button className="quiet" aria-label="Luật chơi" onClick={()=>setModal('rules')}><BookOpen size={17}/><span>Luật chơi</span></button>{hasSession&&<button className="icon" onClick={()=>setModal('leave')} aria-label="Rời màn hình phòng"><LogOut size={18}/></button>}</div></header>
  {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Đóng thông báo"><X size={16}/></button></div>}
  {!hasSession?<div className="lobby-page">
   <section className="intro"><div className="eyebrow"><span className="tiny-line"/> PHÒNG GIAO DỊCH LỊCH SỬ</div><h1>Thị trường đổi.<br/>Bạn <em>quyết định.</em></h1><p className="intro-copy">9 lần Netflix đứng trước bước ngoặt.<br/>Mua thêm, giữ lại, hay rút lui?</p><div className="lobby-stats"><div><b>09</b><span>Vòng quyết định</span></div><div><b>{RULES.seconds}<span>s</span></b><span>Mỗi vòng</span></div><div><b>50</b><span>Người / phòng</span></div></div><div className="stock-ticket"><div className="ticker-logo">N</div><div><strong>NETFLIX, INC.</strong><small>NASDAQ: NFLX · USD</small></div><span className="ticket-end">1 CÔNG TY<br/><b>7 NĂM BIẾN ĐỘNG</b></span></div><div className="intro-foot"><ShieldCheck size={17}/> Cùng vốn ban đầu. Không loại người chơi.</div></section>
   <section className="join-card"><div className="eyebrow">SẴN SÀNG VÀO VỊ THẾ?</div><h2>Tham gia phòng chơi</h2><p>Dùng tên của bạn hoặc tên đội để lên bảng xếp hạng.</p><form onSubmit={ev=>{ev.preventDefault();send('join',{name,code:code.toUpperCase()});}}><label>Tên người chơi / đội<input value={name} onChange={ev=>setName(ev.target.value)} placeholder="Ví dụ: Đội Bắt Đáy" maxLength={24} required autoComplete="nickname"/></label><label>Mã phòng<input className="code-input" value={code} onChange={ev=>setCode(ev.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))} placeholder="ABC123" maxLength={6} minLength={6} required autoComplete="off"/></label><button className="primary wide" disabled={busy||!restored}><Users size={18}/>{busy?'Đang kết nối…':'Vào phòng'}</button></form><div className="or"><span/>hoặc<span/></div><button className="secondary wide" disabled={busy} onClick={()=>send('create')}><Monitor size={18}/>Tạo phòng · Quản trò</button><button className="practice" disabled={busy} onClick={()=>send('create',{solo:true,name:name.trim()||'Bạn'})}><Play size={15}/> Chơi thử một mình</button><div className="small-note">Tạo phòng trên máy chiếu, chia sẻ mã cho cả lớp.<br/>Người chơi chỉ cần mở trình duyệt.</div></section>
  </div>:!s?<section className="loading"><span className="spinner"/><h2>Đang khôi phục phòng…</h2><button className="secondary" onClick={leave}>Về màn hình đầu</button></section>:<div className="game-shell">
   <div className="room-bar"><div className="room-id"><span>PHÒNG</span><b>{s.code}</b><button className="icon" onClick={copy} aria-label="Sao chép link tham gia">{copied?<Check size={17}/>:<Copy size={17}/>}</button></div><div className="room-meta"><span><Users size={16}/>{s.count} / 50</span><span className={online?'connection':'red'}><Radio size={15}/>{online?(s.solo?'Chơi thử':transport):'Mất kết nối'}</span>{s.host&&<span className="host-badge">QUẢN TRÒ</span>}<button className="icon" aria-label="Toàn màn hình" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>{});}}><Maximize2 size={17}/></button></div></div>
   {s.phase==='lobby'?<div className="waiting-grid"><section className="panel waiting"><span className="eyebrow">{s.solo?'SÂN TẬP CỦA BẠN':'SÀN GIAO DỊCH SẮP MỞ'}</span><h1>{s.host?'Mời cả lớp vào vị thế.':'Bạn đã vào phòng.'}</h1><p>{s.host?'Chia sẻ mã phòng. Khi mọi người đã sẵn sàng, bắt đầu vòng đầu tiên.':'Đã giữ chỗ cho '+s.me?.name+'. Chờ quản trò bắt đầu.'}</p><button className="big-code" onClick={copy}>{s.code}<Copy size={26}/></button><span className="muted">{copied?'Đã sao chép link!':'Bấm mã để sao chép link tham gia'}</span><div className="starting"><div><Wallet size={22}/><small>TIỀN MẶT</small><b>{money(rules.cash)}</b></div><span>+</span><div><BarChart3 size={22}/><small>CỔ PHIẾU NFLX</small><b>{new Intl.NumberFormat('vi-VN').format(rules.shares)} CP</b></div></div>{s.host?<button className="primary" disabled={busy||!s.count} onClick={()=>send('start')}><Play size={18}/>Bắt đầu 9 vòng</button>:<div className="wait-status"><span className="spinner"/>Chờ quản trò mở vòng 01</div>}<p className="small-note">{rules.seconds} giây / vòng · Giá đã điều chỉnh chia tách · Mọi người cùng vốn</p></section><aside className="panel roster"><div className="section-head"><h3>Đã vào phòng</h3><span className="pill">{s.count} người</span></div>{!s.count?<div className="empty"><Users size={32}/><p>Người chơi sẽ xuất hiện ở đây.</p></div>:s.players.map((p,i)=><div className="player-row" key={p.id}><span className="avatar">{String(i+1).padStart(2,'0')}</span><strong>{p.name}</strong><Check size={16} className="green"/></div>)}<div className="note"><ShieldCheck size={18}/><span>Tên đã vào phòng được giữ xuyên suốt 9 vòng.</span></div></aside></div>:s.phase==='finished'?<>
    <section className="final-banner"><div><span className="eyebrow">THỊ TRƯỜNG ĐÃ ĐÓNG CỬA</span><h1>Ai giữ được tiền?</h1><p>9 quyết định. Một hành trình từ 2017 đến 2024.</p></div><Trophy size={68} strokeWidth={1.3}/></section><div className="podium">{s.players.slice(0,3).map((p,i)=><section key={p.id} className={'panel winner rank'+i}><div className="eyebrow">{p.rank===1?'NHÀ ĐẦU TƯ DẪN ĐẦU':'HẠNG '+p.rank}</div><h2>{p.name}</h2><div className="big-number">{money(p.wealth)}</div><span className={p.wealth>=initial?'green':'red'}>{pct(p.wealth,initial)}% so với ban đầu</span></section>)}</div>
    <div className="game-grid"><section className="panel"><div className="section-head"><h2>Hành trình đầu tư</h2>{s.host&&s.replays&&<select aria-label="Xem lịch sử người chơi" value={activeReplay?.id||''} onChange={ev=>setReplay(ev.target.value)}>{s.replays.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}</div><Chart values={[initial,...(activeReplay?.snapshots||[]).map(x=>x.portfolio_value_after)]} labels={['Bắt đầu',...(activeReplay?.snapshots||[]).map(x=>'Vòng '+x.round_id)]}/><p className="table-hint">Vuốt ngang bảng để xem đầy đủ danh mục.</p><div className="table-wrap"><table><thead><tr><th>Vòng</th><th>Lệnh</th><th>Số CP giao dịch</th><th>Tiền mặt</th><th>CP đang giữ</th><th>Tổng tài sản</th></tr></thead><tbody>{activeReplay?.snapshots?.map(x=><tr key={x.round_id}><td>{String(x.round_id).padStart(2,'0')}</td><td><span className={'decision-tag '+x.decision.toLowerCase()}>{x.decision}</span>{x.auto&&<small> tự động</small>}</td><td>{new Intl.NumberFormat('vi-VN').format(x.quantity??Math.abs(x.shares_after-x.shares_before))}</td><td>{money(x.cash_after)}</td><td>{x.shares_after}</td><td>{money(x.portfolio_value_after)}</td></tr>)}</tbody></table></div><div className="result-actions"><button className="secondary" onClick={download}><Download size={16}/>Tải nhật ký JSON</button><button className="primary" onClick={leave}><RotateCcw size={16}/>Về sảnh</button></div><details className="debrief"><summary>Câu hỏi thảo luận sau game</summary><p>Bạn có BUY vì thích Squid Game? Có SELL vì ám ảnh cú sập trước đó? Quyết định nào dựa trên dữ liệu, quyết định nào dựa trên cảm xúc?</p><p>Thị trường tạo ra biến động; mức tiền bạn đặt vào cổ phiếu quyết định mức ảnh hưởng. Một kết quả tốt không tự chứng minh một quy trình ra quyết định tốt.</p></details></section><aside><Board s={s}/><section className="panel inflation"><Coins className="gold"/><h3>Sức mua thực</h3><p>{s.me?'Tài sản của bạn':'Tài sản người dẫn đầu'}, quy về USD tháng 4/2017</p><strong>{money(Math.round((s.me?.wealth||s.players[0]?.wealth||0)*s.rules.cpiStart/s.rules.cpiEnd))}</strong><small>CPI-U Mỹ: 244,524 → 308,417.<br/>Chỉ để tham khảo, không đổi thứ hạng.</small><a href={s.rules.cpiSource} target="_blank" rel="noreferrer">Nguồn: U.S. Bureau of Labor Statistics</a></section></aside></div>
   </>:<>
    <div className="round-nav"><div className="round-progress" aria-label="Tiến trình 9 vòng">{Array.from({length:9},(_,i)=><div key={i} className={i===s.round?'current':i<s.round?'done':''} aria-current={i===s.round?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span><i/></div>)}</div><div className={"round-clock "+(remaining<=10&&!reveal?"urgent":"")} role="timer" aria-label={reveal?"Đã chốt kết quả":"Còn "+remaining+" giây"}><Timer size={18}/><b>{reveal?"ĐÃ CHỐT":remaining+"s"}</b></div></div>
    <div className="game-grid play-grid"><div className="main-column"><section key={e.id} className={'event-card panel '+(reveal?'revealed':'')}><div className="event-top"><span className="eyebrow">VÒNG {String(e.id).padStart(2,'0')} / 09 <span className="separator">/</span> {date(e.date)}</span><div className={'timer '+(remaining<=5&&!reveal?'urgent':'')}><Timer size={18}/>{reveal?'ĐÃ CHỐT':remaining+'s'}</div></div><div className="timer-track"><div style={{width:(reveal?0:Math.min(100,remaining/rules.seconds*100))+'%'}}/></div><div className="event-body"><div className="eyebrow muted">{e.eyebrow}</div><h1>{e.title}</h1><ul className="event-facts">{(e.bullets||[e.text]).map((fact,i)=><li key={i}>{fact}</li>)}</ul><div className="metrics">{e.metrics.map(m=><div key={m[1]}><strong>{m[0]}</strong><span>{m[1]}</span></div>)}</div><p className="question">{e.question}</p></div><MarketChart key={e.id} event={e} revealed={reveal}/><div className="execution"><div><span className="n-mark">N</span><b>NFLX</b><small>Giá khớp lệnh mô phỏng</small></div><strong>{money(e.execution)}</strong></div></section>
    {reveal&&<section className="panel reveal-panel"><div className="section-head"><span className="eyebrow">THỊ TRƯỜNG LÊN TIẾNG</span><span className="muted">Đóng cửa {date(e.revealDate)}</span></div><div className="market-move"><strong className={e.reveal>=e.execution?'green':'red'}>{e.reveal>=e.execution?'+':''}{pct(e.reveal,e.execution)}%</strong><div><span>Giá sau sự kiện</span><b>{money(e.reveal)}</b></div></div><p className="lesson">{e.lesson}</p>{s.me&&<div className="pnl"><span>Lãi / lỗ của phần cổ phiếu sau lệnh</span><b className={s.me.delta>=0?'green':'red'}>{money(s.me.delta)}</b></div>}<div className="source-links"><a href={e.priceSource} target="_blank" rel="noreferrer">Nguồn giá · StatMuse</a><a href={e.eventSource} target="_blank" rel="noreferrer">Báo cáo Netflix</a></div>{s.host?<button className="primary wide" disabled={busy} onClick={()=>send('next')}>{s.round===8?<Trophy size={18}/>:<Play size={18}/>} {s.round===8?'Mở bảng tổng kết':'Mở vòng '+String(s.round+2).padStart(2,'0')}</button>:<p className="small-note">Chờ quản trò mở {s.round===8?'bảng tổng kết':'vòng tiếp theo'}.</p>}</section>}
    <section className="panel price-history"><div className="section-head"><h3>Các mốc đã đi qua</h3><span className="muted">NFLX · USD điều chỉnh</span></div><Chart values={[s.rules.reference,...s.history.map(x=>x.reveal)]} labels={['17/04/2017',...s.history.map(x=>date(x.revealDate||x.date))]}/></section></div>
    <aside>{!reveal&&<OrderPanel key={s.round} state={s} remaining={remaining} busy={busy} online={online} onConfirm={order=>send('decide',order)}/>}{s.me&&<section className="panel portfolio"><div className="section-head"><span className="eyebrow">TÀI SẢN CỦA BẠN</span><Wallet size={19}/></div><h2>{money(s.me.wealth)}</h2><span className={s.me.wealth>=initial?'green':'red'}>{pct(s.me.wealth,initial)}% từ lúc bắt đầu</span><div className="allocation"><i style={{width:(s.me.cash/s.me.wealth*100)+'%'}}/></div><div className="balance-row"><span><i className="dot cash"/>Tiền mặt</span><b>{money(s.me.cash)}</b></div><div className="balance-row"><span><i className="dot stock"/>Cổ phiếu NFLX</span><b>{new Intl.NumberFormat('vi-VN').format(s.me.shares)} CP</b></div><div className="note">Hạng #{s.me.rank} · {s.me.name}</div>{s.round>0&&!reveal&&<p className="small-note">Đã tính biến động giá từ mốc trước đến ngày này.</p>}</section>}<Board s={s}/><section className="panel small-card"><ShieldCheck size={20}/><p>Không phải đoán “đáp án đúng”.<br/><b>Hãy quản lý vị thế của bạn.</b></p></section></aside></div>
   </>}
  </div>}
  <footer><span>ĐỪNG ĐỂ TIỀN RƠI <i> / </i> STOCK MARKET EDITION</span><span>Mô phỏng học tập · Không sử dụng tiền thật</span></footer>
  {modal==='rules'&&<Modal title="Luật của sàn" close={closeModal}><Rules rules={rules}/></Modal>}
  {modal==='leave'&&<Modal title="Rời màn hình phòng?" close={closeModal}><p>Để có thể quay lại đúng vị thế, giữ tab này và mở sảnh trong tab mới. Nếu rời ở đây, mã phiên của bạn sẽ bị xóa khỏi tab.</p><div className="result-actions"><button className="secondary" onClick={()=>setModal(null)}>Ở lại</button><button className="primary" onClick={leave}>Rời màn hình</button></div></Modal>}
 </main>;
}
function Board({s}){return <section className="panel leaderboard"><div className="section-head"><h3><Trophy size={17}/>Bảng xếp hạng</h3><span className="pill">{s.count}</span></div><div className="board-label"><span>NHÀ ĐẦU TƯ</span><span>TỔNG TÀI SẢN</span></div><div className="board-list">{s.players.map(p=><div key={p.id} className={'board-row '+(p.id===s.me?.id?'self':'')}><span className={'rank '+(p.rank===1?'gold':'')}>{String(p.rank).padStart(2,'0')}</span><div className="player-name"><strong>{p.name}</strong>{p.decision?<small className={p.decision==='BUY'?'green':p.decision==='SELL'?'red':'gold'}>{p.decision}{p.decision!=='HOLD'&&p.quantity!=null?' · '+new Intl.NumberFormat('vi-VN').format(p.quantity)+' CP':''}</small>:<small>{p.locked?'Đã khóa lệnh':'Đang quan sát'}</small>}</div><b>{money(p.wealth)}</b></div>)}</div><p className="small-note">Xếp hạng theo tổng tài sản, không theo số vòng thắng.</p></section>}
